import { ALL_EMPLOYERS, ALL_SHOPS } from "./categories";
import { comingSoon } from "./define";
import type { TemplateMeta } from "./types";

/**
 * Plantillas registradas en el catálogo que aún no están implementadas.
 * Cuando implementes una, muévela a su carpeta y quítala de esta lista.
 */
export const COMING_SOON: TemplateMeta[] = [
  // ---------------------------------------------------------------- Facturación

  // ---------------------------------------------------------------- Impuestos
  comingSoon("impuestos", {
    slug: "declaracion-mensual-isv",
    title: "Declaración mensual del ISV",
    shortDescription:
      "Hoja de trabajo para calcular débito y crédito fiscal y el ISV a pagar del mes.",
    tier: "pro",
    regulated: "fiscal",
    countries: ["HN"],
  }),
  comingSoon("impuestos", {
    slug: "isr-personas-naturales",
    title: "ISR de personas naturales",
    shortDescription: "Cálculo anual y retención mensual del ISR con la tabla progresiva vigente.",
    tier: "pro",
    regulated: "fiscal",
    countries: ["HN"],
  }),
  comingSoon("impuestos", {
    slug: "control-de-retenciones",
    title: "Control de retenciones",
    shortDescription:
      "Registro de retenciones de ISR e ISV efectuadas y recibidas con constancias.",
    tier: "pro",
    regulated: "fiscal",
    countries: ["HN"],
  }),
  comingSoon("impuestos", {
    slug: "impuesto-municipal",
    title: "Impuesto municipal",
    shortDescription:
      "Estimación del impuesto sobre industria, comercio y servicios según tu municipio.",
    tier: "pro",
    regulated: "fiscal",
    countries: ["HN"],
  }),
  comingSoon("impuestos", {
    slug: "calendario-tributario",
    title: "Calendario tributario",
    shortDescription: "Fechas de vencimiento de declaraciones y pagos del año con recordatorios.",
    tier: "pro",
    regulated: "fiscal",
    countries: ["HN"],
  }),
  comingSoon("impuestos", {
    slug: "flujo-de-caja",
    title: "Flujo de caja",
    shortDescription: "Proyección de entradas y salidas de efectivo por mes con saldo acumulado.",
    tier: "free",
    businessTypes: [...ALL_SHOPS, "servicios", "constructora", "agro"],
  }),
  comingSoon("impuestos", {
    slug: "estado-de-resultados-balance",
    title: "Estado de resultados y balance general",
    shortDescription: "Estados financieros básicos con márgenes e indicadores calculados.",
    tier: "pro",
    regulated: "fiscal",
  }),
  comingSoon("impuestos", {
    slug: "libro-diario-mayor",
    title: "Libro diario y mayor",
    shortDescription:
      "Partidas contables con validación de cuadre y mayorización automática por cuenta.",
    tier: "pro",
    regulated: "fiscal",
  }),
  comingSoon("impuestos", {
    slug: "conciliacion-bancaria",
    title: "Conciliación bancaria",
    shortDescription:
      "Concilia el saldo del banco con tus libros: depósitos en tránsito y cheques pendientes.",
    tier: "free",
  }),
  comingSoon("impuestos", {
    slug: "catalogo-de-cuentas",
    title: "Catálogo de cuentas",
    shortDescription: "Catálogo contable base para pequeñas empresas, editable y con niveles.",
    tier: "free",
  }),
  comingSoon("impuestos", {
    slug: "activos-fijos-depreciacion",
    title: "Activos fijos y depreciación",
    shortDescription: "Registro de activos con depreciación en línea recta mensual y acumulada.",
    tier: "pro",
    regulated: "fiscal",
  }),
  comingSoon("impuestos", {
    slug: "presupuesto-anual",
    title: "Presupuesto anual",
    shortDescription: "Presupuesto de ingresos y gastos por mes comparado contra lo real.",
    tier: "free",
  }),
  comingSoon("impuestos", {
    slug: "punto-de-equilibrio",
    title: "Punto de equilibrio",
    shortDescription: "Calcula cuántas unidades o ventas necesitas para cubrir tus costos.",
    tier: "free",
    businessTypes: [...ALL_SHOPS, "servicios"],
  }),

  // ---------------------------------------------------------------- Planilla
  comingSoon("planilla", {
    slug: "planilla-de-sueldos",
    title: "Planilla de sueldos",
    shortDescription: "Planilla mensual con IHSS, RAP, ISR, deducciones y aportes patronales.",
    tier: "pro",
    regulated: "laboral",
    countries: ["HN"],
    businessTypes: ALL_EMPLOYERS,
  }),
  comingSoon("planilla", {
    slug: "decimo-tercer-y-cuarto-mes",
    title: "Décimo tercer y cuarto mes",
    shortDescription: "Calcula el aguinaldo y el décimo cuarto mes proporcional por empleado.",
    tier: "pro",
    regulated: "laboral",
    countries: ["HN"],
    businessTypes: ALL_EMPLOYERS,
  }),
  comingSoon("planilla", {
    slug: "prestaciones-laborales",
    title: "Prestaciones laborales",
    shortDescription:
      "Preaviso, cesantía, vacaciones y décimos proporcionales al terminar la relación.",
    tier: "pro",
    regulated: "laboral",
    countries: ["HN"],
    businessTypes: ALL_EMPLOYERS,
  }),
  comingSoon("planilla", {
    slug: "horas-extra",
    title: "Horas extra",
    shortDescription: "Registro y pago de horas extra diurnas y nocturnas con los recargos de ley.",
    tier: "pro",
    regulated: "laboral",
    countries: ["HN"],
    businessTypes: ALL_EMPLOYERS,
  }),
  comingSoon("planilla", {
    slug: "salario-minimo",
    title: "Salario mínimo",
    shortDescription:
      "Tabla del salario mínimo por rama y tamaño de empresa y verificador por empleado.",
    tier: "free",
    regulated: "laboral",
    countries: ["HN"],
    businessTypes: ALL_EMPLOYERS,
  }),
  comingSoon("planilla", {
    slug: "control-de-vacaciones",
    title: "Control de vacaciones",
    shortDescription:
      "Días de vacaciones ganados según antigüedad, tomados y pendientes por empleado.",
    tier: "pro",
    regulated: "laboral",
    countries: ["HN"],
    businessTypes: ALL_EMPLOYERS,
  }),
  comingSoon("planilla", {
    slug: "control-de-asistencia",
    title: "Control de asistencia",
    shortDescription: "Asistencia diaria por empleado con ausencias, permisos y resumen del mes.",
    tier: "free",
    businessTypes: ALL_EMPLOYERS,
  }),
  comingSoon("planilla", {
    slug: "horarios-y-turnos",
    title: "Horarios y turnos",
    shortDescription: "Programación semanal de turnos con horas por empleado.",
    tier: "free",
    businessTypes: ["restaurante", "comercio", "farmacia", "clinica", "cafeteria-panaderia"],
  }),
  comingSoon("planilla", {
    slug: "boleta-de-pago",
    title: "Boleta de pago",
    shortDescription: "Boletas individuales con ingresos, deducciones y neto a pagar.",
    tier: "pro",
    regulated: "laboral",
    countries: ["HN"],
    businessTypes: ALL_EMPLOYERS,
  }),
  comingSoon("planilla", {
    slug: "evaluacion-de-desempeno",
    title: "Evaluación de desempeño",
    shortDescription: "Evaluación por competencias con ponderaciones y calificación final.",
    tier: "free",
    businessTypes: ALL_EMPLOYERS,
  }),
  comingSoon("planilla", {
    slug: "prestamos-a-empleados",
    title: "Préstamos a empleados",
    shortDescription: "Control de préstamos y adelantos con cuotas descontadas en planilla.",
    tier: "free",
    businessTypes: ALL_EMPLOYERS,
  }),
  comingSoon("planilla", {
    slug: "comisiones-y-bonos",
    title: "Comisiones y bonos",
    shortDescription: "Cálculo de comisiones escalonadas y bonos por cumplimiento.",
    tier: "pro",
    businessTypes: ["comercio", "servicios", "tienda-ropa", "ferreteria"],
  }),

  // ---------------------------------------------------------------- Inventario
  comingSoon("inventario", {
    slug: "inventario-stock-minimo",
    title: "Inventario con stock mínimo",
    shortDescription: "Existencias con alertas de reorden, valor del inventario y movimientos.",
    tier: "free",
    businessTypes: ALL_SHOPS,
  }),
  comingSoon("inventario", {
    slug: "kardex",
    title: "Kardex",
    shortDescription: "Tarjeta kardex con costo promedio ponderado, entradas, salidas y saldos.",
    tier: "free",
    businessTypes: ALL_SHOPS,
  }),
  comingSoon("inventario", {
    slug: "inventario-por-lote-vencimiento",
    title: "Inventario por lote y vencimiento",
    shortDescription: "Lotes con fecha de vencimiento y alertas de productos por vencer.",
    tier: "pro",
    businessTypes: ["farmacia", "pulperia", "comercio", "cafeteria-panaderia"],
  }),
  comingSoon("inventario", {
    slug: "lista-de-precios-margen",
    title: "Lista de precios con margen",
    shortDescription: "Precios de venta calculados desde el costo, margen deseado e ISV.",
    tier: "free",
    businessTypes: ALL_SHOPS,
  }),
  comingSoon("inventario", {
    slug: "control-de-fiados",
    title: "Control de fiados",
    shortDescription: "Créditos de clientes con abonos, saldos y días de atraso.",
    tier: "free",
    businessTypes: ["pulperia", "comercio", "ferreteria", "farmacia"],
  }),
  comingSoon("inventario", {
    slug: "mercaderia-en-consignacion",
    title: "Mercadería en consignación",
    shortDescription:
      "Productos recibidos o entregados en consignación con ventas y liquidaciones.",
    tier: "pro",
    businessTypes: ["comercio", "tienda-ropa"],
  }),
  comingSoon("inventario", {
    slug: "pedidos-y-entregas",
    title: "Pedidos y entregas",
    shortDescription: "Seguimiento de pedidos con estado, fecha de entrega, anticipos y saldos.",
    tier: "free",
    businessTypes: ["comercio", "cafeteria-panaderia", "restaurante", "tienda-ropa"],
  }),
  comingSoon("inventario", {
    slug: "ventas-por-whatsapp",
    title: "Ventas por WhatsApp",
    shortDescription:
      "Registro de pedidos por WhatsApp y redes con envíos, pagos y clientes frecuentes.",
    tier: "free",
    businessTypes: ["comercio", "tienda-ropa", "cafeteria-panaderia"],
  }),
  comingSoon("inventario", {
    slug: "costos-de-importacion-aduana",
    title: "Costos de importación y aduana",
    shortDescription: "Costo puesto en bodega: FOB, flete, seguro, DAI, ISV y gastos de aduana.",
    tier: "pro",
    regulated: "fiscal",
    countries: ["HN"],
    businessTypes: ["comercio", "ferreteria", "tienda-ropa"],
  }),

  // ---------------------------------------------------------------- Negocios
  comingSoon("negocios", {
    slug: "pulperia",
    title: "Control para pulpería",
    shortDescription:
      "Ventas del día, compras a proveedores, fiados y ganancia diaria en un solo archivo.",
    tier: "free",
    businessTypes: ["pulperia"],
  }),
  comingSoon("negocios", {
    slug: "restaurante-costos-recetas",
    title: "Costos de recetas para restaurante",
    shortDescription: "Costo por porción, precio sugerido y margen de cada platillo.",
    tier: "pro",
    businessTypes: ["restaurante", "cafeteria-panaderia"],
  }),
  comingSoon("negocios", {
    slug: "taller-mecanico",
    title: "Taller mecánico",
    shortDescription: "Órdenes de trabajo con repuestos, mano de obra y estado de cada vehículo.",
    tier: "free",
    businessTypes: ["taller"],
  }),
  comingSoon("negocios", {
    slug: "barberia-salon",
    title: "Barbería y salón de belleza",
    shortDescription: "Servicios del día por estilista con comisiones y propinas.",
    tier: "free",
    businessTypes: ["barberia-salon"],
  }),
  comingSoon("negocios", {
    slug: "ferreteria",
    title: "Control para ferretería",
    shortDescription: "Inventario por categoría, cotizaciones rápidas y ventas al crédito.",
    tier: "free",
    businessTypes: ["ferreteria"],
  }),
  comingSoon("negocios", {
    slug: "farmacia",
    title: "Control para farmacia",
    shortDescription: "Medicamentos por lote, vencimientos y ventas diarias.",
    tier: "pro",
    businessTypes: ["farmacia"],
  }),
  comingSoon("negocios", {
    slug: "transporte-taxis",
    title: "Transporte y taxis",
    shortDescription: "Ingresos diarios por unidad, combustible, mantenimiento y ganancia neta.",
    tier: "free",
    businessTypes: ["transporte"],
  }),
  comingSoon("negocios", {
    slug: "tienda-de-ropa",
    title: "Tienda de ropa",
    shortDescription: "Inventario por talla y color, ventas y apartados.",
    tier: "free",
    businessTypes: ["tienda-ropa"],
  }),
  comingSoon("negocios", {
    slug: "cafeteria-panaderia",
    title: "Cafetería y panadería",
    shortDescription: "Producción diaria, mermas, costos de insumos y ventas.",
    tier: "free",
    businessTypes: ["cafeteria-panaderia"],
  }),
  comingSoon("negocios", {
    slug: "servicios-freelancers",
    title: "Control para freelancers",
    shortDescription: "Proyectos, horas trabajadas, cobros pendientes y ganancia por cliente.",
    tier: "free",
    businessTypes: ["freelancer", "servicios"],
  }),
  comingSoon("negocios", {
    slug: "constructora-presupuesto-de-obra",
    title: "Presupuesto de obra",
    shortDescription: "Presupuesto por renglones con materiales, mano de obra, indirectos e ISV.",
    tier: "pro",
    businessTypes: ["constructora"],
  }),
  comingSoon("negocios", {
    slug: "agricultura-cafe-ganaderia",
    title: "Agricultura, café y ganadería",
    shortDescription: "Costos de producción por manzana, cosecha, ventas y rentabilidad.",
    tier: "free",
    businessTypes: ["agro"],
  }),
  comingSoon("negocios", {
    slug: "camaroneras-pesca",
    title: "Camaroneras y pesca",
    shortDescription: "Siembra, alimento, cosecha por estanque y rendimiento.",
    tier: "pro",
    businessTypes: ["pesca"],
  }),

  // ---------------------------------------------------------------- Educación
  comingSoon("educacion", {
    slug: "pensiones-y-mensualidades",
    title: "Pensiones y mensualidades",
    shortDescription: "Cobro de mensualidades por alumno con saldos y morosidad.",
    tier: "free",
    businessTypes: ["escuela"],
  }),
  comingSoon("educacion", {
    slug: "notas-y-promedios",
    title: "Notas y promedios",
    shortDescription: "Calificaciones por parcial con promedios, aprobados y reprobados.",
    tier: "free",
    businessTypes: ["escuela"],
  }),
  comingSoon("educacion", {
    slug: "asistencia-escolar",
    title: "Asistencia escolar",
    shortDescription: "Lista de asistencia mensual con porcentaje por alumno.",
    tier: "free",
    businessTypes: ["escuela"],
  }),
  comingSoon("educacion", {
    slug: "horario-de-clases",
    title: "Horario de clases",
    shortDescription: "Horario semanal por grado o docente listo para imprimir.",
    tier: "free",
    businessTypes: ["escuela"],
  }),
  comingSoon("educacion", {
    slug: "planificador-de-estudio",
    title: "Planificador de estudio",
    shortDescription: "Plan semanal de estudio con metas y seguimiento.",
    tier: "free",
  }),
  comingSoon("educacion", {
    slug: "pagos-de-academias",
    title: "Pagos de academias",
    shortDescription: "Inscripciones, mensualidades y materiales de academias y cursos.",
    tier: "free",
    businessTypes: ["escuela"],
  }),

  // ---------------------------------------------------------------- Finanzas personales
  comingSoon("finanzas-personales", {
    slug: "presupuesto-mensual",
    title: "Presupuesto mensual",
    shortDescription: "Presupuesto familiar por categorías comparado contra el gasto real.",
    tier: "free",
    businessTypes: ["hogar"],
  }),
  comingSoon("finanzas-personales", {
    slug: "gastos-e-ingresos",
    title: "Gastos e ingresos",
    shortDescription: "Registro diario de gastos e ingresos con resumen por categoría y mes.",
    tier: "free",
    businessTypes: ["hogar", "freelancer"],
  }),
  comingSoon("finanzas-personales", {
    slug: "deudas-y-tarjetas",
    title: "Deudas y tarjetas",
    shortDescription:
      "Control de deudas y tarjetas con plan bola de nieve y fecha estimada de pago.",
    tier: "free",
    businessTypes: ["hogar"],
  }),
  comingSoon("finanzas-personales", {
    slug: "simulador-de-prestamos",
    title: "Simulador de préstamos",
    shortDescription: "Tabla de amortización con cuota nivelada, intereses y saldo por mes.",
    tier: "free",
    businessTypes: ["hogar", "comercio"],
  }),
  comingSoon("finanzas-personales", {
    slug: "ahorro-por-metas",
    title: "Ahorro por metas",
    shortDescription: "Metas de ahorro con aportes mensuales, avance y fecha estimada.",
    tier: "free",
    businessTypes: ["hogar"],
  }),
  comingSoon("finanzas-personales", {
    slug: "control-de-remesas",
    title: "Control de remesas",
    shortDescription: "Remesas recibidas en dólares, tipo de cambio, lempiras y en qué se usaron.",
    tier: "free",
    businessTypes: ["hogar"],
  }),
  comingSoon("finanzas-personales", {
    slug: "prestamo-de-vivienda",
    title: "Préstamo de vivienda",
    shortDescription: "Amortización hipotecaria con seguros, abonos extra y ahorro en intereses.",
    tier: "free",
    businessTypes: ["hogar"],
  }),
  comingSoon("finanzas-personales", {
    slug: "comprar-vs-alquilar",
    title: "Comprar o alquilar vivienda",
    shortDescription: "Compara el costo total de comprar contra alquilar a varios años.",
    tier: "free",
    businessTypes: ["hogar"],
  }),
  comingSoon("finanzas-personales", {
    slug: "jubilacion",
    title: "Plan de jubilación",
    shortDescription: "Proyección de ahorro para el retiro con aportes e intereses.",
    tier: "free",
    businessTypes: ["hogar"],
  }),
  comingSoon("finanzas-personales", {
    slug: "pagos-de-servicios",
    title: "Pagos de servicios",
    shortDescription: "Energía, agua, internet, teléfono y más: vencimientos y pagos por mes.",
    tier: "free",
    businessTypes: ["hogar"],
  }),
  comingSoon("finanzas-personales", {
    slug: "presupuesto-de-bodas-eventos",
    title: "Presupuesto de bodas y eventos",
    shortDescription: "Presupuesto por rubro, proveedores, anticipos e invitados.",
    tier: "free",
    businessTypes: ["hogar"],
  }),
  comingSoon("finanzas-personales", {
    slug: "lista-del-super",
    title: "Lista del súper",
    shortDescription: "Lista de compras por pasillo con precios estimados y total.",
    tier: "free",
    businessTypes: ["hogar"],
  }),

  // ---------------------------------------------------------------- Comunidad
  comingSoon("comunidad", {
    slug: "cuotas-patronato",
    title: "Cuotas de patronato",
    shortDescription: "Cuotas mensuales por vivienda con pagos, morosos y gastos del patronato.",
    tier: "free",
    businessTypes: ["iglesia-ong"],
  }),
  comingSoon("comunidad", {
    slug: "contabilidad-de-iglesias",
    title: "Contabilidad de iglesias",
    shortDescription: "Diezmos, ofrendas, donaciones y gastos con informe mensual.",
    tier: "free",
    businessTypes: ["iglesia-ong"],
  }),
  comingSoon("comunidad", {
    slug: "cajas-de-ahorro-cooperativas",
    title: "Caja de ahorro y caja rural",
    shortDescription: "Aportes de socios, préstamos internos, intereses y reparto de utilidades.",
    tier: "free",
    businessTypes: ["iglesia-ong", "agro"],
  }),
  comingSoon("comunidad", {
    slug: "rifas-y-colectas",
    title: "Rifas y colectas",
    shortDescription: "Números vendidos, pagos pendientes, premios y fondos recaudados.",
    tier: "free",
    businessTypes: ["iglesia-ong", "escuela"],
  }),
  comingSoon("comunidad", {
    slug: "aportes-asociaciones",
    title: "Aportes de asociaciones",
    shortDescription: "Aportaciones de miembros, actividades y rendición de cuentas.",
    tier: "free",
    businessTypes: ["iglesia-ong"],
  }),
  comingSoon("comunidad", {
    slug: "administracion-de-condominios",
    title: "Administración de condominios",
    shortDescription: "Cuotas de mantenimiento, gastos comunes y estado de cuenta por unidad.",
    tier: "pro",
    businessTypes: ["inmobiliaria"],
  }),

  // ---------------------------------------------------------------- Bienes raíces
  comingSoon("bienes-raices", {
    slug: "control-de-alquileres",
    title: "Control de alquileres",
    shortDescription: "Inquilinos, rentas mensuales, pagos atrasados y depósitos.",
    tier: "free",
    businessTypes: ["inmobiliaria", "hogar"],
  }),
  comingSoon("bienes-raices", {
    slug: "contrato-de-arrendamiento",
    title: "Datos de contrato de arrendamiento",
    shortDescription: "Ficha de contratos con fechas, montos, ajustes y renovaciones.",
    tier: "free",
    businessTypes: ["inmobiliaria"],
  }),
  comingSoon("bienes-raices", {
    slug: "gastos-de-propiedades",
    title: "Gastos de propiedades",
    shortDescription: "Gastos de mantenimiento, impuestos y servicios por propiedad.",
    tier: "free",
    businessTypes: ["inmobiliaria"],
  }),
  comingSoon("bienes-raices", {
    slug: "rentabilidad-inmobiliaria",
    title: "Rentabilidad inmobiliaria",
    shortDescription: "Rentabilidad bruta y neta, retorno de la inversión y años de recuperación.",
    tier: "pro",
    businessTypes: ["inmobiliaria"],
  }),
  comingSoon("bienes-raices", {
    slug: "ventas-de-lotes-a-plazos",
    title: "Venta de lotes a plazos",
    shortDescription: "Lotes vendidos con prima, cuotas, pagos recibidos y saldo de cada cliente.",
    tier: "pro",
    businessTypes: ["inmobiliaria"],
  }),

  // ---------------------------------------------------------------- Emprendedores
  comingSoon("emprendedores", {
    slug: "plan-de-negocio-12-meses",
    title: "Plan de negocio a 12 meses",
    shortDescription: "Proyección de ventas, costos y utilidades para tu plan de negocio.",
    tier: "pro",
  }),
  comingSoon("emprendedores", {
    slug: "costos-de-producto",
    title: "Costos de producto",
    shortDescription: "Costo unitario con materiales, mano de obra y gastos, y precio sugerido.",
    tier: "free",
    businessTypes: ["comercio", "cafeteria-panaderia", "freelancer"],
  }),
  comingSoon("emprendedores", {
    slug: "calendario-de-contenido",
    title: "Calendario de contenido",
    shortDescription: "Publicaciones por red social, fecha, formato y estado.",
    tier: "free",
  }),
  comingSoon("emprendedores", {
    slug: "campanas-y-resultados",
    title: "Campañas y resultados",
    shortDescription: "Inversión en anuncios, alcance, clientes y costo por resultado.",
    tier: "free",
  }),
  comingSoon("emprendedores", {
    slug: "crm-simple",
    title: "CRM simple",
    shortDescription: "Clientes potenciales, seguimiento, etapa de venta y próximos pasos.",
    tier: "free",
    businessTypes: ["servicios", "freelancer", "inmobiliaria"],
  }),
  comingSoon("emprendedores", {
    slug: "metas-de-ventas",
    title: "Metas de ventas",
    shortDescription: "Metas mensuales contra ventas reales con porcentaje de cumplimiento.",
    tier: "free",
  }),
  comingSoon("emprendedores", {
    slug: "plan-de-lanzamiento",
    title: "Plan de lanzamiento",
    shortDescription: "Tareas, responsables y fechas para lanzar un producto.",
    tier: "free",
  }),

  // ---------------------------------------------------------------- Salud
  comingSoon("salud", {
    slug: "citas-y-pacientes",
    title: "Citas y pacientes",
    shortDescription: "Agenda de citas con pacientes, motivo, estado y cobro.",
    tier: "free",
    businessTypes: ["clinica"],
  }),
  comingSoon("salud", {
    slug: "historial-de-consultas",
    title: "Historial de consultas",
    shortDescription: "Historial por paciente con diagnóstico, tratamiento y seguimiento.",
    tier: "free",
    businessTypes: ["clinica"],
  }),
  comingSoon("salud", {
    slug: "medicamentos-y-vencimientos",
    title: "Medicamentos y vencimientos",
    shortDescription: "Medicamentos con dosis, horarios, existencias y fechas de vencimiento.",
    tier: "free",
    businessTypes: ["clinica", "farmacia", "hogar"],
  }),
  comingSoon("salud", {
    slug: "seguimiento-de-salud",
    title: "Seguimiento de salud",
    shortDescription: "Presión, glucosa, peso y otros indicadores con alertas.",
    tier: "free",
    businessTypes: ["hogar"],
  }),
  comingSoon("salud", {
    slug: "planificador-de-comidas-y-rutinas",
    title: "Planificador de comidas y rutinas",
    shortDescription: "Menú semanal, lista de compras y rutina de ejercicio.",
    tier: "free",
    businessTypes: ["hogar"],
  }),
];
