import { z } from "zod";

import { BRAND_HEX } from "@/lib/excel/styles";
import { defineForm } from "@/templates/define";
import {
  SECTION_CONTENT,
  SECTION_DESIGN,
  businessFields,
  colorField,
  exampleField,
  paperField,
} from "@/templates/shared/fields";
import {
  hexColor,
  imageDataUrl,
  isoDate,
  optionalInt,
  paper,
  rowsCount,
  stringList,
  taxIdText,
  text,
} from "@/templates/shared/schema";

const SECTION_NUMBERING = "Numeración y datos SAR";

export const configSchema = z.object({
  businessName: text(80),
  taxId: taxIdText,
  address: text(120),
  phone: text(40),
  email: text(80),
  logo: imageDataUrl,
  color: hexColor,
  prefix: text(30),
  startNumber: z.coerce.number({ error: "Escribe un número" }).int().min(1).max(99_999_999),
  cai: text(60),
  rangeFrom: optionalInt(),
  rangeTo: optionalInt(),
  deadline: isoDate,
  lines: rowsCount(5, 100),
  optionalColumns: z.array(z.enum(["code", "discount", "unit"])),
  defaultRate: z.enum(["standard", "special", "exempt", "exonerated"]),
  paymentMethods: stringList(12, 40),
  amountInWords: z.boolean(),
  exemptionFields: z.boolean(),
  notes: text(300),
  paper,
  example: z.boolean(),
});

export type FacturaConfig = z.infer<typeof configSchema>;

export const form = defineForm<FacturaConfig>({
  configSchema,
  defaultConfig: (ctx) => ({
    businessName: "",
    taxId: "",
    address: "",
    phone: "",
    email: "",
    logo: "",
    color: BRAND_HEX,
    prefix: ctx.invoicing.defaultPrefix,
    startNumber: 1,
    cai: "",
    rangeFrom: null,
    rangeTo: null,
    deadline: "",
    lines: 15,
    optionalColumns: ["discount"],
    defaultRate: "standard",
    paymentMethods: ["Efectivo", "Tarjeta", "Transferencia", "Cheque"],
    amountInWords: true,
    exemptionFields: false,
    notes: "Gracias por su compra.",
    paper: "letter",
    example: false,
  }),
  formFields: [
    ...businessFields(),
    {
      type: "text",
      name: "prefix",
      label: "Prefijo de numeración",
      description: "Establecimiento - punto de emisión - tipo de documento.",
      placeholder: "000-001-01-",
      maxLength: 30,
      section: SECTION_NUMBERING,
    },
    {
      type: "number",
      name: "startNumber",
      label: "Correlativo inicial",
      min: 1,
      step: 1,
      section: SECTION_NUMBERING,
    },
    {
      type: "text",
      name: "cai",
      label: "CAI (opcional)",
      placeholder: "XXXXXX-XXXXXX-XXXXXX-XXXXXX-XXXXXX-XX",
      maxLength: 60,
      section: SECTION_NUMBERING,
      fullWidth: true,
    },
    {
      type: "number",
      name: "rangeFrom",
      label: "Rango autorizado: desde",
      description: "Correlativo inicial autorizado (opcional).",
      min: 0,
      step: 1,
      section: SECTION_NUMBERING,
    },
    {
      type: "number",
      name: "rangeTo",
      label: "Rango autorizado: hasta",
      min: 0,
      step: 1,
      section: SECTION_NUMBERING,
    },
    {
      type: "date",
      name: "deadline",
      label: "Fecha límite de emisión (opcional)",
      section: SECTION_NUMBERING,
    },
    {
      type: "number",
      name: "lines",
      label: "Cantidad de líneas",
      min: 5,
      max: 100,
      step: 1,
      section: SECTION_CONTENT,
    },
    {
      type: "select",
      name: "defaultRate",
      label: "Tasa de ISV predeterminada por línea",
      description: "Cada línea se puede cambiar en el archivo con una lista desplegable.",
      options: (ctx) =>
        ctx.taxes.salesTax.rates.map((r) => ({
          value: r.id,
          label: `${r.label} — ${r.description}`,
        })),
      section: SECTION_CONTENT,
    },
    {
      type: "multiselect",
      name: "optionalColumns",
      label: "Columnas opcionales",
      options: [
        { value: "code", label: "Código de producto" },
        { value: "unit", label: "Unidad de medida" },
        { value: "discount", label: "Descuento por línea" },
      ],
      section: SECTION_CONTENT,
      fullWidth: true,
    },
    {
      type: "list",
      name: "paymentMethods",
      label: "Formas de pago",
      description: "Aparecen como lista desplegable en la factura.",
      itemPlaceholder: "Ej. Transferencia",
      maxItems: 12,
      addLabel: "Agregar forma de pago",
      section: SECTION_CONTENT,
      fullWidth: true,
    },
    {
      type: "switch",
      name: "amountInWords",
      label: "Total en letras",
      section: SECTION_CONTENT,
    },
    {
      type: "switch",
      name: "exemptionFields",
      label: "Campos para clientes exonerados",
      description: "Orden de compra exenta, constancia de exonerado y registro SAG.",
      section: SECTION_CONTENT,
    },
    {
      type: "textarea",
      name: "notes",
      label: "Nota al pie",
      rows: 2,
      maxLength: 300,
      section: SECTION_CONTENT,
      fullWidth: true,
    },
    colorField,
    paperField,
    { ...exampleField, section: SECTION_DESIGN },
  ],
});
