/**
 * Catálogo de cuentas base para pequeñas empresas (estructura contable
 * general, no es un valor legal). Código jerárquico: 1 dígito = grupo,
 * 2 = subgrupo, 4 = cuenta de mayor, 6 = subcuenta.
 */
export const ACCOUNT_TYPES = [
  { digit: "1", type: "Activo", nature: "Deudora", statement: "Balance general" },
  { digit: "2", type: "Pasivo", nature: "Acreedora", statement: "Balance general" },
  { digit: "3", type: "Patrimonio", nature: "Acreedora", statement: "Balance general" },
  { digit: "4", type: "Ingresos", nature: "Acreedora", statement: "Estado de resultados" },
  { digit: "5", type: "Costos", nature: "Deudora", statement: "Estado de resultados" },
  { digit: "6", type: "Gastos", nature: "Deudora", statement: "Estado de resultados" },
];

export const BASE_ACCOUNTS: [string, string][] = [
  ["1", "Activo"],
  ["11", "Activo corriente"],
  ["1101", "Caja general"],
  ["1102", "Caja chica"],
  ["1103", "Bancos"],
  ["1104", "Cuentas por cobrar a clientes"],
  ["1105", "Estimación para cuentas incobrables"],
  ["1106", "Inventario de mercadería"],
  ["1107", "ISV crédito fiscal"],
  ["1108", "Anticipos y pagos a cuenta de impuestos"],
  ["1109", "Gastos pagados por anticipado"],
  ["12", "Activo no corriente"],
  ["1201", "Terrenos"],
  ["1202", "Edificios e instalaciones"],
  ["1203", "Mobiliario y equipo de oficina"],
  ["1204", "Equipo de cómputo"],
  ["1205", "Vehículos"],
  ["1206", "Maquinaria y equipo"],
  ["1207", "Depreciación acumulada"],
  ["1208", "Depósitos en garantía"],
  ["2", "Pasivo"],
  ["21", "Pasivo corriente"],
  ["2101", "Proveedores"],
  ["2102", "Acreedores diversos"],
  ["2103", "ISV débito fiscal"],
  ["2104", "ISV por pagar"],
  ["2105", "Retenciones por pagar"],
  ["2106", "IHSS por pagar"],
  ["2107", "RAP por pagar"],
  ["2108", "Sueldos por pagar"],
  ["2109", "Préstamos bancarios a corto plazo"],
  ["2110", "ISR por pagar"],
  ["22", "Pasivo no corriente"],
  ["2201", "Préstamos bancarios a largo plazo"],
  ["2202", "Provisión para prestaciones laborales"],
  ["3", "Patrimonio"],
  ["31", "Capital"],
  ["3101", "Capital social"],
  ["3102", "Aportes de socios"],
  ["32", "Resultados"],
  ["3201", "Utilidades retenidas"],
  ["3202", "Utilidad o pérdida del ejercicio"],
  ["3203", "Reserva legal"],
  ["4", "Ingresos"],
  ["41", "Ingresos de operación"],
  ["4101", "Ventas"],
  ["4102", "Devoluciones y descuentos sobre ventas"],
  ["4103", "Ingresos por servicios"],
  ["42", "Otros ingresos"],
  ["4201", "Ingresos financieros"],
  ["4202", "Otros ingresos"],
  ["5", "Costos"],
  ["51", "Costo de ventas"],
  ["5101", "Costo de la mercadería vendida"],
  ["5102", "Fletes sobre compras"],
  ["6", "Gastos"],
  ["61", "Gastos de administración"],
  ["6101", "Sueldos y salarios"],
  ["6102", "Décimo tercer y cuarto mes"],
  ["6103", "Aportes patronales (IHSS, RAP, INFOP)"],
  ["6104", "Alquileres"],
  ["6105", "Energía eléctrica"],
  ["6106", "Agua"],
  ["6107", "Teléfono e internet"],
  ["6108", "Papelería y útiles"],
  ["6109", "Honorarios profesionales"],
  ["6110", "Depreciaciones"],
  ["6111", "Mantenimiento y reparaciones"],
  ["62", "Gastos de venta"],
  ["6201", "Publicidad y propaganda"],
  ["6202", "Comisiones sobre ventas"],
  ["6203", "Combustible y transporte"],
  ["63", "Gastos financieros"],
  ["6301", "Intereses bancarios"],
  ["6302", "Comisiones bancarias"],
  ["64", "Impuestos"],
  ["6401", "Impuesto sobre la renta"],
  ["6402", "Impuestos municipales"],
];

export const accountTypeOf = (code: string) => ACCOUNT_TYPES.find((t) => code.startsWith(t.digit));

export const levelOf = (code: string) =>
  code.length === 1 ? 1 : code.length === 2 ? 2 : code.length <= 4 ? 3 : 4;
